### ISSUE TITLE
Resume Filtering

### ISSUE THREAD

**Issue by ASankaran** [ASankaran/core#3]
Currently the resume book displays all resumes in an ordered table. We should add the abilility to filter resume's based on all the metadata that we have associated with them. We should also allow for sorting the resumes based on a specified field of the metadata.

This can be done by having the resume book endpoint take a filter in the query string which is uses to decide which resumes to render into the template.

On the front end there needs to be form on the resume book page which allows setting filtering options. Submitting the form should reload the page with the correct filter as a query parameter.

**Comment by apappu9** [comment]
I can do this
